=== mitraillet/ScrabbleJava/ScrabbleJavaExecutable/ressource/dataCaseDTD.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT plateau (ligne)+ >

<!ELEMENT ligne (case)+ >

<!ELEMENT case (x+, y+, bonus+) >

<!ELEMENT x (#PCDATA) >
<!ELEMENT y (#PCDATA) >
<!ELEMENT bonus (#PCDATA) >

=== mitraillet/ScrabbleJava/ScrabbleJavaExecutable/ressource/dataCase.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plateau SYSTEM "./dataCaseDTD.dtd">
<plateau>
	<ligne>
		<case>
			<x>0</x>
			<y>0</y>
			<bonus>4</bonus>
		</case>
		<case>
			<x>1</x>
			<y>0</y>
			<bonus>0</bonus>
		</case>
		<case>
			<x>2</x>
			<y>0</y>
			<bonus>0</bonus>
		</case>
		<case>
			<x>3</x>
			<y>0</y>
			<bonus>1</bonus>
		</case>
		<case>
			<x>4</x>
			<y>0</y>
			<bonus>0</bonus>
		</case>
		<case>
			<x>5</x>
			<y>0</y>
			<bonus>0</bonus>
		</case>
		<case>
			<x>6</x>
			<y>0</y>
			<bonus>0</bonus>
		</case>
		<case>
			<x>7</x>
			<y>0</y>
			<bonus>4</bonus>
		</case>
		<case>
			<x>8</x>
			<y>0</y>
			<bonus>0</bonus>
		</case>
		<case>
			<x>9</x>
			<y>0</y>
			<bonus>0</bonus>
		</case>
		<case>
			<x>10</x>
			<y>0</y>
			<bonus>0</bonus>
		</case>
		<case>
			<x>11</x>
			<y>0</y>
			<bonus>1</bonus>
		</case>
		<case>
			<x>12</x>
			<y>0</y>
			<bonus>0</bonus>
		</case>
		<case>
			<x>13</x>
			<y>0</y>
			<bonus>0</bonus>
		</case>
		<case>
			<x>14</x>
			<y>0</y>
			<bonus>4</bonus>
		</case>
	</ligne>
	
	<ligne>
		<case>
			<x>0</x>
			<y>1</y>
			<bonus>0</bonus>
		</case>
		<case>
			<x>1</x>
			<y>1</y>
			<bonus>3</bonus>
		</case>
		<case>
			<x>2</x>
			<y>1</y>
			<bonus>0</bonus>
		</case>
		<case>
			<x>3</x>
			<y>1</y>
			<bonus>0</bonus>
		</case>
		<case>
			<x>4</x>
			<y>1</y>
			<bonus>0</bonus>
		</case>
		<case>
			<x>5</x>
			<y>1</y>
			<bonus>2</bonus>
		</case>
		<case>
			<x>6</x>
			<y>1</y>
			<bonus>0</bonus>
		</case>
		<case>
			<x>7</x>
			<y>1</y>
			<bonus>0</bonus>
		</case>
		<case>
			<x>8</x>
			<y>1</y>
			<bonus>0</bonus>
		</case>
		<case>
			<x>9</x>
			<y>1</y>
			<bonus>2</bonus>
		</case>
		<case>
			<x>10</x>
			<y>1</y>
			<bonus>0</bonus>
		</case>
		<case>
			<x>11</x>
			<y>1</y>
			<bonus>0</bonus>
		</case>
		<case>
			<x>12</x>
			<y>1</y>
			<bonus>0</bonus>
		</case>
		<case>
			<x>13</x>
			<y>1</y>
			<bonus>3</bonus>
		</case>
		<case>
			<x>14</x>
			<y>1</y>
			<bonus>0</bonus>
		</case>
	</ligne>
	
	<ligne>
		<case>
			<x>0</x>
			<y>2</y>
			<bonus>0</bonus>
		</case>
		<case>
			<x>1</x>
			<y>2</y>
			<bonus>0</bonus>
		</case>
		<case>
			<x>2</x>
			<y>2</y>
			<bonus>3</bonus>
		</case>
		<case>
			<x>3</x>
			<y>2</y>
			<bonus>0</bonus>
		</case>
		<case>
			<x>4</x>
			<y>2</y>
			<bonus>0</bonus>
		</case>
		<case>
			<x>5</x>
			<y>2</y>
			<bonus>0</bonus>
		</case>
		<case>
			<x>6</x>
			<y>2</y>
			<bonus>1</bonus>
		</case>
		<case>
			<x>7</x>
			<y>2</y>
			<bonus>0</bonus>
		</case>
		<case>
			<x>8</x>
			<y>2</y>
			<bonus>1</bonus>
		</case>
		<case>
			<x>9</x>
			<y>2</y>
			<bonus>0</bonus>
		</case>
		<case>
			<x>10</x>
			<y>2</y>
			<bonus>0</bonus>
		</case>
		<case>
			<x>11</x>
			<y>2</y>
			<bonus>0</bonus>
		</case>
		<case>
			<x>12</x>
			<y>2</y>
			<bonus>3</bonus>
		</case>
		<case>
			<x>13</x>
			<y>2</y>
			<bonus>0</bonus>
		</case>
		<case>
			<x>14</x>
			<y>2</y>
			<bonus>0</bonus>
		</case>
	</ligne>
	
	<ligne>
		<case>
			<x>0</x>
			<y>3</y>
			<bonus>1</bonus>
		</case>
		<case>
			<x>1</x>
			<y>3</y>
			<bonus>0</bonus>
		</case>
		<case>
			<x>2</x>
			<y>3</y>
			<bonus>0</bonus>
		</case>
		<case>
			<x>3</x>
			<y>3</y>
			<bonus>3</bonus>
		</case>
		<case>
			<x>4</x>
			<y>3</y>
			<bonus>0</bonus>
		</case>
		<case>
			<x>5</x>
			<y>3</y>
			<bonus>0</bonus>
		</case>
		<case>
			<x>6</x>
			<y>3</y>
			<bonus>0</bonus>
		</case>
		<case>
			<x>7</x>
			<y>3</y>
			<bonus>1</bonus>
		</case>
		<case>
			<x>8</x>
			<y>3</y>
			<bonus>0</bonus>
		</case>
		<case>
			<x>9</x>
			<y>3</y>
			<bonus>0</bonus>
		</case>
		<case>
			<x>10</x>
			<y>3</y>
			<bonus>0</bonus>
		</case>
		<case>
			<x>11</x>
			<y>3</y>
			<bonus>3</bonus>
		</case>
		<case>
			<x>12</x>
			<y>3</y>
			<bonus>0</bonus>
		</case>
		<case>
			<x>13</x>
			<y>3</y>
			<bonus>0</bonus>
		</case>
		<case>
			<x>14</x>
			<y>3</y>
			<bonus>1</bonus>
		</case>
	</ligne>
	
	<ligne>
		<case>
			<x>0</x>
			<y>4</y>
			<bonus>0</bonus>
		</case>
		<case>
			<x>1</x>
			<y>4</y>
			<bonus>0</bonus>
		</case>
		<case>
			<x>2</x>
			<y>4</y>
			<bonus>0</bonus>
		</case>
		<case>
			<x>3</x>
			<y>4</y>
			<bonus>0</bonus>
		</case>
		<case>
			<x>4</x>
			<y>4</y>
			<bonus>3</bonus>
		</case>
		<case>
			<x>5</x>
			<y>4</y>
			<bonus>0</bonus>
		</case>
		<case>
			<x>6</x>
			<y>4</y>
			<bonus>0</bonus>
		</case>
		<case>
			<x>7</x>
			<y>4</y>
			<bonus>0</bonus>
		</case>
		<case>
			<x>8</x>
			<y>4</y>
			<bonus>0</bonus>
		</case>
		<case>
			<x>9</x>
			<y>4</y>
			<bonus>0</bonus>
		</case>
		<case>
			<x>10</x>
			<y>4</y>
			<bonus>3</bonus>
		</case>
		<case>
			<x>11</x>
			<y>4</y>
			<bonus>0</bonus>
		</case>
		<case>
			<x>12</x>
			<y>4</y>
			<bonus>0</bonus>
		</case>
		<case>
			<x>13</x>
			<y>4</y>
			<bonus>0</bonus>
		</case>
		<case>
			<x>14</x>
			<y>4</y>
			<bonus>0</bonus>
		</case>
	</ligne>
	
	<ligne>
		<case>
			<x>0</x>
			<y>5</y>
			<bonus>0</bonus>
		</case>
		<case>
			<x>1</x>
			<y>5</y>
			<bonus>2</bonus>
		</case>
		<case>
			<x>2</x>
			<y>5</y>
			<bonus>0</bonus>
		</case>
		<case>
			<x>3</x>
			<y>5</y>
			<bonus>0</bonus>
		</case>
		<case>
			<x>4</x>
			<y>5</y>
			<bonus>0</bonus>
		</case>
		<case>
			<x>5</x>
			<y>5</y>
			<bonus>2</bonus>
		</case>
		<case>
			<x>6</x>
			<y>5</y>
			<bonus>0</bonus>
		</case>
		<case>
			<x>7</x>
			<y>5</y>
			<bonus>0</bonus>
		</case>
		<case>
			<x>8</x>
			<y>5</y>
			<bonus>0</bonus>
		</case>
		<case>
			<x>9</x>
			<y>5</y>
			<bonus>2</bonus>
		</case>
		<case>
			<x>10</x>
			<y>5</y>
			<bonus>0</bonus>
		</case>
		<case>
			<x>11</x>
			<y>5</y>
			<bonus>0</bonus>
		</case>
		<case>
			<x>12</x>
			<y>5</y>
			<bonus>0</bonus>
		</case>
		<case>
			<x>13</x>
			<y>5</y>
			<bonus>2</bonus>
		</case>
		<case>
			<x>14</x>
			<y>5</y>
			<bonus>0</bonus>
		</case>
	</ligne>
	
	<ligne>
		<case>
			<x>0</x>
			<y>6</y>
			<bonus>0</bonus>
		</case>
		<case>
			<x>1</x>
			<y>6</y>
			<bonus>0</bonus>
		</case>
		<case>
			<x>2</x>
			<y>6</y>
			<bonus>1</bonus>
		</case>
		<case>
			<x>3</x>
			<y>6</y>
			<bonus>0</bonus>
		</case>
		<case>
			<x>4</x>
			<y>6</y>
			<bonus>0</bonus>
		</case>
		<case>
			<x>5</x>
			<y>6</y>
			<bonus>0</bonus>
		</case>
		<case>
			<x>6</x>
			<y>6</y>
			<bonus>1</bonus>
		</case>
		<case>
			<x>7</x>
			<y>6</y>
			<bonus>0</bonus>
		</case>
		<case>
			<x>8</x>
			<y>6</y>
			<bonus>1</bonus>
		</case>
		<case>
			<x>9</x>
			<y>6</y>
			<bonus>0</bonus>
		</case>
		<case>
			<x>10</x>
			<y>6</y>
			<bonus>0</bonus>
		</case>
		<case>
			<x>11</x>
			<y>6</y>
			<bonus>0</bonus>
		</case>
		<case>
			<x>12</x>
			<y>6</y>
			<bonus>1</bonus>
		</case>
		<case>
			<x>13</x>
			<y>6</y>
			<bonus>0</bonus>
		</case>
		<case>
			<x>14</x>
			<y>6</y>
			<bonus>0</bonus>
		</case>
	</ligne>
	
	<ligne>
		<case>
			<x>0</x>
			<y>7</y>
			<bonus>4</bonus>
		</case>
		<case>
			<x>1</x>
			<y>7</y>
			<bonus>0</bonus>
		</case>
		<case>
			<x>2</x>
			<y>7</y>
			<bonus>0</bonus>
		</case>
		<case>
			<x>3</x>
			<y>7</y>
			<bonus>1</bonus>
		</case>
		<case>
			<x>4</x>
			<y>7</y>
			<bonus>0</bonus>
		</case>
		<case>
			<x>5</x>
			<y>7</y>
			<bonus>0</bonus>
		</case>
		<case>
			<x>6</x>
			<y>7</y>
			<bonus>0</bonus>
		</case>
		<case>
			<x>7</x>
			<y>7</y>
			<bonus>5</bonus>
		</case>
		<case>
			<x>8</x>
			<y>7</y>
			<bonus>0</bonus>
		</case>
		<case>
			<x>9</x>
			<y>7</y>
			<bonus>0</bonus>
		</case>
		<case>
			<x>10</x>
			<y>7</y>
			<bonus>0</bonus>
		</case>
		<case>
			<x>11</x>
			<y>7</y>
			<bonus>1</bonus>
		</case>
		<case>
			<x>12</x>
			<y>7</y>
			<bonus>0</bonus>
		</case>
		<case>
			<x>13</x>
			<y>7</y>
			<bonus>0</bonus>
		</case>
		<case>
			<x>14</x>
			<y>7</y>
			<bonus>4</bonus>
		</case>
	</ligne>
	
	<ligne>
		<case>
			<x>0</x>
			<y>8</y>
			<bonus>0</bonus>
		</case>
		<case>
			<x>1</x>
			<y>8</y>
			<bonus>0</bonus>
		</case>
		<case>
			<x>2</x>
			<y>8</y>
			<bonus>1</bonus>
		</case>
		<case>
			<x>3</x>
			<y>8</y>
			<bonus>0</bonus>
		</case>
		<case>
			<x>4</x>
			<y>8</y>
			<bonus>0</bonus>
		</case>
		<case>
			<x>5</x>
			<y>8</y>
			<bonus>0</bonus>
		</case>
		<case>
			<x>6</x>
			<y>8</y>
			<bonus>1</bonus>
		</case>
		<case>
			<x>7</x>
			<y>8</y>
			<bonus>0</bonus>
		</case>
		<case>
			<x>8</x>
			<y>8</y>
			<bonus>1</bonus>
		</case>
		<case>
			<x>9</x>
			<y>8</y>
			<bonus>0</bonus>
		</case>
		<case>
			<x>10</x>
			<y>8</y>
			<bonus>0</bonus>
		</case>
		<case>
			<x>11</x>
			<y>8</y>
			<bonus>0</bonus>
		</case>
		<case>
			<x>12</x>
			<y>8</y>
			<bonus>1</bonus>
		</case>
		<case>
			<x>13</x>
			<y>8</y>
			<bonus>0</bonus>
		</case>
		<case>
			<x>14</x>
			<y>8</y>
			<bonus>0</bonus>
		</case>
	</ligne>
	
	<ligne>
		<case>
			<x>0</x>
			<y>9</y>
			<bonus>0</bonus>
		</case>
		<case>
			<x>1</x>
			<y>9</y>
			<bonus>2</bonus>
		</case>
		<case>
			<x>2</x>
			<y>9</y>
			<bonus>0</bonus>
		</case>
		<case>
			<x>3</x>
			<y>9</y>
			<bonus>0</bonus>
		</case>
		<case>
			<x>4</x>
			<y>9</y>
			<bonus>0</bonus>
		</case>
		<case>
			<x>5</x>
			<y>9</y>
			<bonus>2</bonus>
		</case>
		<case>
			<x>6</x>
			<y>9</y>
			<bonus>0</bonus>
		</case>
		<case>
			<x>7</x>
			<y>9</y>
			<bonus>0</bonus>
		</case>
		<case>
			<x>8</x>
			<y>9</y>
			<bonus>0</bonus>
		</case>
		<case>
			<x>9</x>
			<y>9</y>
			<bonus>2</bonus>
		</case>
		<case>
			<x>10</x>
			<y>9</y>
			<bonus>0</bonus>
		</case>
		<case>
			<x>11</x>
			<y>9</y>
			<bonus>0</bonus>
		</case>
		<case>
			<x>12</x>
			<y>9</y>
			<bonus>0</bonus>
		</case>
		<case>
			<x>13</x>
			<y>9</y>
			<bonus>2</bonus>
		</case>
		<case>
			<x>14</x>
			<y>9</y>
			<bonus>0</bonus>
		</case>
	</ligne>
	
	<ligne>
		<case>
			<x>0</x>
			<y>10</y>
			<bonus>0</bonus>
		</case>
		<case>
			<x>1</x>
			<y>10</y>
			<bonus>0</bonus>
		</case>
		<case>
			<x>2</x>
			<y>10</y>
			<bonus>0</bonus>
